apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
  annotations:
    haproxy.router.openshift.io/timeout: 60s  
spec:
  auth:
    strategy: openshift
  deployment:
    cluster_wide_access: true
    accessible_namespaces:
      - "**"
    namespace: istio-system
    pod_labels:
      sidecar.istio.io/inject: 'false'
  external_services:
    grafana:
      enabled: false
    istio:
      config_map_name: istio
      istio_sidecar_injector_config_map_name: istio-sidecar-injector
      istiod_deployment_name: istiod
      url_service_version: 'http://istiod.istio-system:15014/version'
      component_status:
        components:
        - app_label: "istiod"
          is_core: true
          is_proxy: false
        enabled: true
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      query_scope:
        mesh_id: ossm-3
      thanos_proxy:
        enabled: true
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    tracing:
      enabled: true
      auth:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        insecure_skip_verify: true
        type: bearer
        use_kiali_token: true
      query_timeout: 60
      internal_url: 'http://tempo-sample-query-frontend.tracing-system.svc.cluster.local:3200'
      provider: tempo
      health_check_url: 'http://tempo-sample-query-frontend.tracing-system.svc.cluster.local:3200'
      use_grpc: true
      grpc_port: 9095
      external_url: 'http://tempo-sample-query-frontend.tracing-system.svc.cluster.local:3200'
      tempo_config:
        org_id: "1"
        cache_enabled: true
        cache_capacity: 200
  installation_tag: "Kiali [istio-system]"
  istio_namespace: istio-system
  server:
    write_timeout: 60
